// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLoggerAPI.Data;

#nullable disable

namespace ShiftsLoggerAPI.Migrations
{
    [DbContext(typeof(ShiftsDbContext))]
    partial class ShiftsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");
#pragma warning restore 612, 618
        }
    }
}
